"use client"
import type { Metadata } from "next"
import "@fontsource/poppins"
import "@fontsource/poppins/700.css"
import "@fontsource/poppins/600.css"
import "@fontsource/poppins/500.css"
import "./globals.css"
import Header from "./_components/Header"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import Footer from "./_components/Footer"
import { ClerkProvider } from "@clerk/nextjs"

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const queryClient = new QueryClient()

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <QueryClientProvider client={queryClient}>
                        {!window.location.pathname.includes("sign-in") &&
                            !window.location.pathname.includes("sign-up") && (
                                <Header />
                            )}
                        {children}
                        {!window.location.pathname.includes("sign-in") &&
                            !window.location.pathname.includes("sign-up") && (
                                <Footer />
                            )}
                    </QueryClientProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
